"""initial

Revision ID: b441134d47dd
Revises: 
Create Date: 2026-03-28 20:51:30.360909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b441134d47dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('line_display_name', sa.String(length=128), nullable=True),
    sa.Column('line_picture_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('guest', 'user', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'disabled', name='user_status'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_line_user_id'), 'users', ['line_user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('edit_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', name='edit_action'), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_histories_user_id'), 'edit_histories', ['user_id'], unique=False)
    op.create_table('email_filters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filter_type', sa.Enum('sender', 'domain', 'subject_pattern', name='email_filter_type'), nullable=False),
    sa.Column('filter_value', sa.String(length=256), nullable=False),
    sa.Column('action', sa.Enum('important', 'exclude', name='email_filter_action'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'filter_type', 'filter_value', name='uq_email_filter')
    )
    op.create_index(op.f('ix_email_filters_user_id'), 'email_filters', ['user_id'], unique=False)
    op.create_table('event_color_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('business', 'private', name='event_type_enum'), nullable=False),
    sa.Column('confirmation_status', sa.Enum('confirmed', 'tentative', name='confirmation_status_enum'), nullable=False),
    sa.Column('color_id', sa.String(length=16), nullable=False),
    sa.Column('color_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', 'confirmation_status', name='uq_event_color_rule')
    )
    op.create_index(op.f('ix_event_color_rules_user_id'), 'event_color_rules', ['user_id'], unique=False)
    op.create_table('memo_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_memo_category_user_name')
    )
    op.create_index(op.f('ix_memo_categories_user_id'), 'memo_categories', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('morning_summary_time', sa.Time(), nullable=False),
    sa.Column('morning_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_intervals', sa.ARRAY(sa.Integer()), server_default='{30,15,5}', nullable=True),
    sa.Column('unreplied_threshold_days', sa.Integer(), nullable=False),
    sa.Column('unreplied_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('line', 'gmail', 'gcalendar', name='oauth_provider'), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_user_provider')
    )
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_table('unreplied_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(length=128), nullable=False),
    sa.Column('content_memo', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unreplied_items_user_id'), 'unreplied_items', ['user_id'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'image', 'url', name='content_type'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_ocr_text', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('url_title', sa.Text(), nullable=True),
    sa.Column('url_summary', sa.Text(), nullable=True),
    sa.Column('url_thumbnail', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['memo_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_category_id'), 'memos', ['category_id'], unique=False)
    op.create_index(op.f('ix_memos_user_id'), 'memos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memos_user_id'), table_name='memos')
    op.drop_index(op.f('ix_memos_category_id'), table_name='memos')
    op.drop_table('memos')
    op.drop_index(op.f('ix_unreplied_items_user_id'), table_name='unreplied_items')
    op.drop_table('unreplied_items')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_memo_categories_user_id'), table_name='memo_categories')
    op.drop_table('memo_categories')
    op.drop_index(op.f('ix_event_color_rules_user_id'), table_name='event_color_rules')
    op.drop_table('event_color_rules')
    op.drop_index(op.f('ix_email_filters_user_id'), table_name='email_filters')
    op.drop_table('email_filters')
    op.drop_index(op.f('ix_edit_histories_user_id'), table_name='edit_histories')
    op.drop_table('edit_histories')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_line_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
