#!/bin/bash
set -euo pipefail

# LINE Developers チャネル設定ガイド

echo "=== LINE Developers チャネル設定 ==="
echo ""
echo "LINE Developers Console: https://developers.line.biz/console/"
echo ""
echo "────────────────────────────────────"
echo "1. Messaging API チャネル作成"
echo "────────────────────────────────────"
echo "  - Provider を選択（なければ新規作成）"
echo "  - 「Messaging API」チャネルを作成"
echo "    - Channel name: LINE AI Secretary"
echo "    - Channel description: AI個人秘書サービス"
echo "    - Category: ユーティリティ"
echo ""
echo "  設定後に取得:"
echo "    - Channel Secret → LINE_CHANNEL_SECRET"
echo "    - Channel Access Token（長期）→ LINE_CHANNEL_ACCESS_TOKEN"
echo ""
echo "  Webhook設定:"
echo "    - Webhook URL: https://YOUR_CLOUD_RUN_URL/api/line/webhook"
echo "    - Use webhook: ON"
echo "    - Auto-reply messages: OFF"
echo "    - Greeting messages: OFF"
echo ""
echo "────────────────────────────────────"
echo "2. LINE Login チャネル作成"
echo "────────────────────────────────────"
echo "  - 同じProviderで「LINE Login」チャネルを作成"
echo "    - Channel name: LINE AI Secretary Login"
echo "    - App types: Web app"
echo ""
echo "  設定後に取得:"
echo "    - Channel ID → LINE_LOGIN_CHANNEL_ID"
echo "    - Channel Secret → LINE_LOGIN_CHANNEL_SECRET"
echo ""
echo "  Callback URL設定:"
echo "    - https://YOUR_FRONTEND_URL/login"
echo "    - http://localhost:3847/login (開発用)"
echo ""
echo "────────────────────────────────────"
echo "3. 環境変数設定"
echo "────────────────────────────────────"
echo ""
echo "backend/.env.local:"
echo "  LINE_CHANNEL_SECRET=xxx"
echo "  LINE_CHANNEL_ACCESS_TOKEN=xxx"
echo "  LINE_LOGIN_CHANNEL_ID=xxx"
echo "  LINE_LOGIN_CHANNEL_SECRET=xxx"
echo ""
echo "frontend/.env.local:"
echo "  VITE_LINE_LOGIN_CHANNEL_ID=xxx"
echo "  VITE_LINE_LOGIN_REDIRECT_URI=http://localhost:3847/login"
echo ""
echo "────────────────────────────────────"
echo "4. GCP Secret Manager に登録"
echo "────────────────────────────────────"
echo "  gcloud secrets create LINE_CHANNEL_SECRET --data-file=- <<< 'VALUE'"
echo "  gcloud secrets create LINE_CHANNEL_ACCESS_TOKEN --data-file=- <<< 'VALUE'"
echo "  gcloud secrets create LINE_LOGIN_CHANNEL_ID --data-file=- <<< 'VALUE'"
echo "  gcloud secrets create LINE_LOGIN_CHANNEL_SECRET --data-file=- <<< 'VALUE'"
