#!/bin/bash
set -euo pipefail

# ドメイン・SSL設定ガイド

echo "=== ドメイン・SSL設定 ==="
echo ""
echo "────────────────────────────────────"
echo "1. Cloud Run カスタムドメイン（バックエンド）"
echo "────────────────────────────────────"
echo "  # ドメインマッピング作成"
echo "  gcloud beta run domain-mappings create \\"
echo "    --service=line-ai-secretary-api \\"
echo "    --domain=api.YOUR_DOMAIN.com \\"
echo "    --region=asia-northeast1"
echo ""
echo "  # DNS設定（表示されるレコードをDNSに追加）"
echo "  # CNAME: api.YOUR_DOMAIN.com → ghs.googlehosted.com"
echo ""
echo "  # SSL証明書は自動的にプロビジョニングされます（Let's Encrypt）"
echo ""
echo "────────────────────────────────────"
echo "2. Vercel カスタムドメイン（フロントエンド）"
echo "────────────────────────────────────"
echo "  # Vercel ダッシュボードで設定:"
echo "  # Settings → Domains → Add Domain"
echo "  # ドメイン: app.YOUR_DOMAIN.com"
echo ""
echo "  # DNS設定:"
echo "  # CNAME: app.YOUR_DOMAIN.com → cname.vercel-dns.com"
echo ""
echo "  # SSL証明書は自動的にプロビジョニングされます"
echo ""
echo "────────────────────────────────────"
echo "3. LINE Developers Webhook URL 更新"
echo "────────────────────────────────────"
echo "  Messaging API チャネル:"
echo "    Webhook URL: https://api.YOUR_DOMAIN.com/api/line/webhook"
echo ""
echo "  LINE Login チャネル:"
echo "    Callback URL: https://app.YOUR_DOMAIN.com/login"
echo ""
echo "────────────────────────────────────"
echo "4. 環境変数更新"
echo "────────────────────────────────────"
echo "  backend:"
echo "    FRONTEND_URL=https://app.YOUR_DOMAIN.com"
echo ""
echo "  frontend:"
echo "    VITE_API_URL=https://api.YOUR_DOMAIN.com"
echo "    VITE_LINE_LOGIN_REDIRECT_URI=https://app.YOUR_DOMAIN.com/login"
